### PR TITLE
3.2-201602 fixed pom.xml

### PR DESCRIPTION
**Pull request by domdorn**
as requested in https://github.com/webjars/webjars/issues/1341, i've adjusted the pom.xml to correctly download the files from upstream and create the jar.

### CODE REVIEW

**Comment by jamesward** [comment]
@domdorn Now that I can see the payload I'm not seeing why this should be a WebJar.  This doesn't seem like a JS / web lib.  Can you tell me more about what the 51degrees-lite library is?

**Comment by domdorn** [comment]
51degrees is a library which allows to detect browser features on the server-side.
This is done by passing the user-agent string to a method, which in turn looks up the browser in a database (and using some heuristics) which is provided with data files.
It allows to detect stuff like "OS", "OS Version", "Browser", "Browser Version", "IsMobile" and others. 

They have a commercial offering and a "lite" version. The commercial offering updates the database files on a weekly basis, the "lite" version features only a limited database, which is updated on a monthly basis.
While the commercial offering offers a "auto-update" feature, the "lite" version does not.
Using the lite-version, the user has to manually download the database files every month, has to replace them in a place accessible to the webapp, restart the webapp and so on. 

The provided webjar basically downloads these database files from the github repo, renames them to a consistent filename and provide them on the classpath. This way, the only thing a developer has to do to update to the current version of the database files, is, to change the version string of the dependency in his build.sbt file and trigger a new build. 

I know, that those database files are not a webjar in the sense of "provide jquery as a jar to include in the app and serve it to the end-user". However, this library is crucial if you need the ability to detect browser features on the server by looking at the user-agent. As this is primary used in WebApps, the use as a WebJar seems appropriate to me.. I hope you see the benefit as well.

**Comment by domdorn** [comment]
Hi James, any updates from your side? 

Thanks,
Dominik

**Comment by jamesward** [comment]
I don't think this library fits with the mission of WebJars since it is for server-side usage.  WebJars are all static assets for the client-side.

Although you should be able to take this Maven package and setup your own Maven Central OSS artifact and deploy it on your own.

**Pull request merged**
